name: Test deploy                    # Workflow 이름
on:                                  # Event 감
  push:
    branches:
      - main
jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest
    
    env:                # 환경 변수 설정
      CI: false         # CI 환경 변수를 false로 설정.
      
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3
        
      - name: .env setting
        run: |
          echo "REACT_APP_SERVER_URL=${{ secrets.REACT_APP_SERVER_URL }}" >> .env
          
      - name: Install dependencies    # 의존 파일 설치
        run: npm install
        
      - name: Generate build          # React Build 
        run: npm run build

      - name: Upload to S3             # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp \
            --recursive \
            build s3://capstone-s3-s3-bucket
